[package]
name = "library_loader"
version = "0.1.0"
authors = ["Kurt Cancemi <kurt@x64architecture.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.77"
structopt = "0.3.17"
regex = "1"