[package]
name = "test_library"
version = "0.1.0"
authors = ["Kurt Cancemi <kurt@x64architecture.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "test_library"
crate-type = ["dylib"]
